apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          policy.kyverno.io/synchronize: enable
          env: nonprod
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: workload-nonprod
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/engineering-dev
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          