configs:
  rbac:
    policy.default: 'role:readonly'
  cm:
    users.anonymous.enabled: "true"
    timeout.reconciliation: 10s
  params:
    server.insecure: true
    application.namespaces: "*"
  repositories:
    gitops:
      url: https://github.com/joaquinrz/flamingo-lab.git
      name: gitops
      type: git
server:
  image:
    repository: ghcr.io/flux-subsystem-argo/fsa/argocd
    tag: v2.8.4-fl.21-main-6c72e98c
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: flamingo.kubelab.pro
    hosts: 
    - flamingo.kubelab.pro
    tls:
      - secretName: argocd-tls
        hosts:
          - flamingo.kubelab.pro
    https: true
