apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-workload
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          policy.kyverno.io/synchronize: enable  
  template:
    metadata:
      name: '{{name}}-prometheus'
    spec:
      project: workload-infra
      sources:
      - repoURL: 'https://prometheus-community.github.io/helm-charts/'
        targetRevision: "45.10.1"
        chart: kube-prometheus-stack
        helm:
          values: |
            prometheus:
              enabled: true
              prometheusSpec:
                externalLabels:
                  region: southcentralus
                  cluster: {{name}}
                remoteWrite:
                - url: "http://receive.thanos.kubelab.pro/api/v1/receive"
                  name: Thanos
          valueFiles:
          - $values/gitops/workload/infra/monitoring/prometheus-workload-values.yaml
      - repoURL: https://github.com/joaquinrz/flamingo-lab.git
        targetRevision: main
        ref: values
      destination:
        server: '{{server}}'
        namespace: prometheus
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
