apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vclusters-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: nonprod-westus1
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: nonprod-eastus1
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: nonprod-eastus2
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: prod-westus1
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: prod-eastus1
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: prod-southus1        
  template:
    metadata:
      name: '{{workload-cluster}}'
    spec:
      project: clusters
      source:
        repoURL: 'https://charts.loft.sh/'
        targetRevision: 0.15.7
        chart: vcluster-k8s
        helm:
          values: |
            sync:
              ingresses:
                enabled: true
      destination:
        server: '{{url}}'
        namespace: '{{workload-cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
